name: CI

on:
  push:
    branches:
      - windows-test
      # - main
      # - dev
  pull_request:
    branches:
      - windows-test
      # - main
      # - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      config: "Release"

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration $config --no-restore

      - name: Test net9.0
        run: dotnet test src/NetCoreForce.Client.Tests --configuration $config --no-restore --no-build --verbosity normal --framework net9.0

      - name: Test net48
        run: dotnet test src/NetCoreForce.Client.Tests --configuration $config --no-restore --no-build --verbosity normal --framework net48
